github=https://github.com/adrianmikula/JakartaMigrationMCP
github.issues=https://github.com/adrianmikula/JakartaMigrationMCP/issues
github.sponsor=https://github.com/sponsors/adrianmikula
linkedin=https://linkedin.com/in/adrianmikula
plugin.page=https://plugins.jetbrains.com/plugin/30093-jakarta-migration-javax--jakarta-
plugin.updates=https://plugins.jetbrains.com/plugin/30093-jakarta-migration-javax--jakarta-/versions
marketplace=https://plugins.jetbrains.com/plugin/30093-jakarta-migration-javax--jakarta-
