package adrianmikula.jakartamigration.pdfreporting.snippet;

import adrianmikula.jakartamigration.pdfreporting.service.PdfReportService;

import java.util.ArrayList;
import java.util.List;

/**
 * Factory for creating HTML snippets for Refactoring Action reports.
 * Generates snippets using real scan data from ComprehensiveScanResults.
 */
public class RefactoringSnippetFactory {

    /**
     * Create a list of HTML snippets for a Refactoring Action report.
     * All snippets use real scan data - no estimates or hardcoded values.
     *
     * @param request The refactoring action report request with real scan data
     * @return List of HTML snippets ordered for report generation
     */
    public List<HtmlSnippet> createSnippets(PdfReportService.RefactoringActionReportRequest request) {
        List<HtmlSnippet> snippets = new ArrayList<>();

        // Section 1: Header - always included
        snippets.add(new HeaderSnippet(
            request.projectName(),
            request.reportTitle(),
            "Refactoring Action Report"
        ));

        // Section 2: Scan Summary - displays actual scan statistics only
        if (request.scanResults() != null) {
            ScanSummarySnippet scanSummary = new ScanSummarySnippet(request.scanResults());
            if (scanSummary.isApplicable()) {
                snippets.add(scanSummary);
            }
        }

        // Section 3: Recipe Recommendations - displays actual recipe data with confidence scores
        if (request.recipeRecommendations() != null && !request.recipeRecommendations().isEmpty()) {
            snippets.add(new RecipeRecommendationsEnhancedSnippet(request.recipeRecommendations()));
        }

        // Section 4: Scan Findings by Category - displays actual findings from each scanner
        if (request.scanResults() != null) {
            ScanFindingsByCategorySnippet findingsByCategory = new ScanFindingsByCategorySnippet(request.scanResults());
            if (findingsByCategory.isApplicable()) {
                snippets.add(findingsByCategory);
            }
        }

        // Section 5: Scanner Recommendations - displays recommendations generated by scanners
        if (request.scanResults() != null) {
            ScannerRecommendationsSnippet scannerRecs = new ScannerRecommendationsSnippet(request.scanResults());
            if (scannerRecs.isApplicable()) {
                snippets.add(scannerRecs);
            }
        }

        return snippets;
    }
}
