package adrianmikula.jakartamigration.pdfreporting.snippet;

import adrianmikula.jakartamigration.advancedscanning.domain.ComprehensiveScanResults;

import java.util.List;

/**
 * HTML snippet displaying scanner-generated recommendations.
 * Displays actual recommendation strings from ComprehensiveScanResults only.
 *
 * References: docs/spec/html-refactoring-report-requirements.md Section 5
 */
public class ScannerRecommendationsSnippet extends BaseHtmlSnippet {

    private final ComprehensiveScanResults scanResults;

    public ScannerRecommendationsSnippet(ComprehensiveScanResults scanResults) {
        this.scanResults = scanResults;
    }

    @Override
    public String getSnippetName() {
        return "Scanner Recommendations";
    }

    @Override
    public String generate() throws SnippetGenerationException {
        if (scanResults == null || scanResults.recommendations() == null || scanResults.recommendations().isEmpty()) {
            return generateNoRecommendationsMessage();
        }

        List<String> recommendations = scanResults.recommendations();

        StringBuilder listItems = new StringBuilder();
        for (String recommendation : recommendations) {
            if (recommendation != null && !recommendation.isBlank()) {
                listItems.append(String.format("                    <li>%s</li>%n", escapeHtml(recommendation)));
            }
        }

        if (listItems.isEmpty()) {
            return generateNoRecommendationsMessage();
        }

        return String.format("""
            <div class="section">
                <h2>Scanner Recommendations</h2>
                <p>Recommendations generated by the code scanners based on detected patterns.</p>
                
                <div class="recommendations-container">
                    <ol class="recommendations-list">
%s                    </ol>
                </div>
            </div>
            """, listItems);
    }

    private String generateNoRecommendationsMessage() {
        return """
            <div class="section">
                <h2>Scanner Recommendations</h2>
                <div class="no-data-message">
                    <p>No scanner recommendations available.</p>
                </div>
            </div>
            """;
    }

    @Override
    public boolean isApplicable() {
        return scanResults != null &&
               scanResults.recommendations() != null &&
               !scanResults.recommendations().isEmpty();
    }

    @Override
    public int getOrder() {
        return 50; // After scan findings
    }
}
