package adrianmikula.jakartamigration.intellij.plugin

import io.kotest.core.spec.style.DescribeSpec
import io.kotest.matchers.shouldBe
import io.kotest.matchers.shouldNotBe
import io.kotest.matchers.shouldContain
import io.kotest.matchers.shouldNotContain
import io.kotest.property.Arb
import io.kotest.property.CheckConfig
import io.kotest.property.PropertyTesting
import io.kotest.property.forAll
import org.junit.jupiter.api.Test
import org.w3c.dom.Document
import org.w3c.dom.Element
import org.w3c.dom.NodeList
import java.io.File
import java.util.jar.JarFile
import javax.xml.parsers.DocumentBuilder
import javax.xml.parsers.DocumentBuilderFactory

/**
 * Tests to verify that the IntelliJ plugin compatibility range is set correctly.
 * Ensures that the untilBuild attribute is properly excluded to allow
 * compatibility with all future IntelliJ versions.
 */
class PluginCompatibilityTest : DescribeSpec({

    describe("Plugin XML compatibility configuration") {
        
        it("should not contain untilBuild attribute in generated plugin.xml") {
            // Given: The plugin.xml file generated by the build process
            val pluginXml = File("src/main/resources/META-INF/plugin.xml")
            
            pluginXml.exists() shouldBe true
            
            // When: We parse the plugin.xml file
            val docBuilderFactory = DocumentBuilderFactory.newInstance()
            val docBuilder: DocumentBuilder = docBuilderFactory.newDocumentBuilder()
            val doc: Document = docBuilder.parse(pluginXml)
            
            // Then: The idea-version element should not have untilBuild attribute
            val ideaVersionElements = doc.getElementsByTagName("idea-version")
            ideaVersionElements.length shouldBe 1
            
            val ideaVersion = ideaVersionElements.item(0) as Element
            val untilBuildAttribute = ideaVersion.getAttribute("until-build")
            
            // The untilBuild attribute should be empty (not set)
            untilBuildAttribute shouldBe ""
        }
        
        it("should contain sinceBuild attribute with correct value") {
            // Given: The plugin.xml file generated by the build process
            val pluginXml = File("src/main/resources/META-INF/plugin.xml")
            
            pluginXml.exists() shouldBe true
            
            // When: We parse the plugin.xml file
            val docBuilderFactory = DocumentBuilderFactory.newInstance()
            val docBuilder: DocumentBuilder = docBuilderFactory.newDocumentBuilder()
            val doc: Document = docBuilder.parse(pluginXml)
            
            // Then: The idea-version element should have sinceBuild attribute
            val ideaVersionElements = doc.getElementsByTagName("idea-version")
            ideaVersionElements.length shouldBe 1
            
            val ideaVersion = ideaVersionElements.item(0) as Element
            val sinceBuildAttribute = ideaVersion.getAttribute("since-build")
            
            // The sinceBuild attribute should be set to 233
            sinceBuildAttribute shouldBe "233"
            sinceBuildAttribute shouldNotBe ""
        }
        
        it("should have exactly one idea-version element") {
            // Given: The plugin.xml file generated by the build process
            val pluginXml = File("src/main/resources/META-INF/plugin.xml")
            
            pluginXml.exists() shouldBe true
            
            // When: We parse the plugin.xml file
            val docBuilderFactory = DocumentBuilderFactory.newInstance()
            val docBuilder: DocumentBuilder = docBuilderFactory.newDocumentBuilder()
            val doc: Document = docBuilder.parse(pluginXml)
            
            // Then: There should be exactly one idea-version element
            val ideaVersionElements = doc.getElementsByTagName("idea-version")
            ideaVersionElements.length shouldBe 1
        }
        
        it("should not contain any untilBuild attributes anywhere in the file") {
            // Given: The plugin.xml file content as text
            val pluginXml = File("src/main/resources/META-INF/plugin.xml")
            
            pluginXml.exists() shouldBe true
            
            // When: We read the file content
            val content = pluginXml.readText()
            
            // Then: The content should not contain any untilBuild references
            content shouldNotContain "until-build"
            content shouldNotContain "untilBuild"
        }
        
        it("should not bundle org.jetbrains.concurrency package in plugin JAR") {
            // Given: The built plugin JAR file
            val buildDir = File("build/libs")
            val pluginJar = buildDir.listFiles()?.find { 
                it.name.endsWith(".jar") && 
                it.name.contains("jakarta-migration") && 
                !it.name.contains("-sources") && 
                !it.name.contains("-javadoc")
            }
            
            // If no JAR found, skip test (build not run yet)
            if (pluginJar == null) {
                println("Skipping JAR verification test - no plugin JAR found. Run buildPlugin first.")
                return@it
            }
            
            pluginJar.exists() shouldBe true
            
            // When: We examine the JAR contents
            val jarFile = JarFile(pluginJar)
            val entries = jarFile.entries().toList()
            jarFile.close()
            
            // Then: The JAR should not contain any org.jetbrains.concurrency classes
            val concurrencyEntries = entries.filter { 
                it.name.startsWith("org/jetbrains/concurrency/") 
            }
            
            concurrencyEntries shouldBe emptyList<String>()
            
            // Also verify no IDE internal packages are bundled
            val ideInternalPackages = entries.filter { entry ->
                entry.name.startsWith("org/jetbrains/") && 
                (entry.name.contains("/internal/") || 
                 entry.name.contains("/util/") ||
                 entry.name.contains("/concurrency/"))
            }
            
            // Allow only specific safe packages
            val allowedPackages = setOf(
                "org/jetbrains/annotations/",
                "org/jetbrains/plugins/"
            )
            
            val problematicPackages = ideInternalPackages.filter { entry ->
                !allowedPackages.any { entry.name.startsWith(it) }
            }
            
            problematicPackages shouldBe emptyList<String>()
        }
        
        it("should verify plugin distribution does not contain IDE packages") {
            // Given: The built plugin distribution
            val distributionsDir = File("build/distributions")
            val pluginZip = distributionsDir.listFiles()?.find { 
                it.name.endsWith(".zip") && it.name.contains("jakarta-migration")
            }
            
            // If no ZIP found, skip test (publishPlugin not run yet)
            if (pluginZip == null) {
                println("Skipping distribution verification test - no plugin ZIP found. Run publishPlugin first.")
                return@it
            }
            
            pluginZip.exists() shouldBe true
            
            // When: We examine the ZIP contents (basic verification)
            // Note: Full ZIP extraction would require additional libraries
            // For now, we verify the JAR inside the ZIP follows the same rules
            
            // Then: The ZIP should exist and be reasonable size
            pluginZip.length() shouldBeGreaterThan 1000L // At least 1KB
            pluginZip.length() shouldBeLessThan 50_000_000L // Less than 50MB (reasonable limit)
        }
    }
    
    describe("Gradle build configuration verification") {
        
        it("should have patchPluginXml configuration in build.gradle.kts") {
            // Given: The build.gradle.kts file
            val buildGradle = File("build.gradle.kts")
            
            buildGradle.exists() shouldBe true
            
            // When: We read the build.gradle.kts content
            val content = buildGradle.readText()
            
            // Then: The content should contain the patchPluginXml configuration
            content shouldContain "patchPluginXml {"
            content shouldContain "sinceBuild.set(providers.gradleProperty(\"intellij.sinceBuild\").orElse(\"233\"))"
            content shouldContain "untilBuild.set(providers.gradleProperty(\"intellij.untilBuild\").orElse(\"\"))"
        }
        
        it("should use providers.gradleProperty for configuration") {
            // Given: The build.gradle.kts file
            val buildGradle = File("build.gradle.kts")
            
            buildGradle.exists() shouldBe true
            
            // When: We read the build.gradle.kts content
            val content = buildGradle.readText()
            
            // Then: The content should use providers.gradleProperty for proper configuration
            content shouldContain "providers.gradleProperty"
            content shouldContain "intellij.sinceBuild"
            content shouldContain "intellij.untilBuild"
        }
    }
    
    describe("Property-based configuration testing") {
        
        it("should handle empty untilBuild property correctly") {
            // Property testing for various untilBuild values
            forAll<String>(
                100,
                CheckConfig(includeEdgeCases = true)
            ) { untilBuildValue ->
                // Given: A mock untilBuild property value
                val mockProperty = untilBuildValue
                
                // When: We simulate the patchPluginXml logic
                val result = if (mockProperty.isEmpty()) "" else mockProperty
                
                // Then: Empty values should result in empty string
                if (untilBuildValue.isEmpty()) {
                    result shouldBe ""
                } else {
                    result shouldBe untilBuildValue
                }
            }
        }
        
        it("should handle sinceBuild property fallback correctly") {
            // Property testing for various sinceBuild values
            forAll<String>(
                100,
                CheckConfig(includeEdgeCases = true)
            ) { sinceBuildValue ->
                // Given: A mock sinceBuild property value
                val mockProperty = sinceBuildValue
                
                // When: We simulate the patchPluginXml logic with fallback
                val result = if (mockProperty.isEmpty()) "233" else mockProperty
                
                // Then: Empty values should result in fallback "233"
                if (sinceBuildValue.isEmpty()) {
                    result shouldBe "233"
                } else {
                    result shouldBe sinceBuildValue
                }
            }
        }
        
        it("should verify plugin.xml in published release ZIP") {
            // Given: The publishPlugin task should generate a release ZIP
            // This test verifies the plugin.xml inside the built distribution
            
            // When: We check for the built plugin distribution
            val buildDir = File("build/distributions")
            val pluginZip = buildDir.listFiles()?.find { it.name.endsWith(".zip") && it.name.contains("jakarta-migration") }
            
            // Then: The plugin ZIP should exist (if publishPlugin has been run)
            // Note: This test may not find the file if publishPlugin hasn't been run yet
            // It's designed to be run after a successful build
            if (pluginZip != null) {
                pluginZip.exists() shouldBe true
                
                // Verify the ZIP contains plugin.xml without untilBuild
                // Note: In a real test environment, we'd extract and verify
                // For now, we verify the source plugin.xml which is what gets packaged
                val sourcePluginXml = File("src/main/resources/META-INF/plugin.xml")
                sourcePluginXml.exists() shouldBe true
                
                val content = sourcePluginXml.readText()
                content shouldNotContain "until-build"
                content shouldNotContain "untilBuild"
                content shouldContain "since-build=\"233\""
            } else {
                // Skip test if no ZIP found (publishPlugin not run)
                println("Skipping ZIP verification test - no plugin ZIP found. Run publishPlugin first.")
            }
        }
    }
})
