package adrianmikula.jakartamigration.intellij.ui;

import adrianmikula.jakartamigration.pdfreporting.service.impl.HtmlToPdfReportServiceImpl;
import adrianmikula.jakartamigration.pdfreporting.service.PdfReportService;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Path;
import java.nio.file.Files;
import java.util.Collections;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Debug test to examine the HTML generated by the snippet-based architecture.
 */
public class SnippetDebugTest {
    
    @Test
    void testSnippetHtmlGeneration() throws Exception {
        // Arrange - Create a minimal request with null dependency graph (Eclipse project case)
        Path outputPath = Path.of("test-output.html");
        
        PdfReportService.RiskAnalysisReportRequest request = new PdfReportService.RiskAnalysisReportRequest(
            outputPath,
            "Test Project",
            "Test Report",
            null, // dependencyGraph - this is the Eclipse project case
            null, // analysisReport
            null, // scanResults
            null, // platformScanResults
            null, // riskScore
            "Incremental",
            Collections.emptyMap(),
            Collections.emptyMap(),
            Collections.emptyList(),
            Collections.emptyList(),
            Collections.emptyMap(),
            Collections.emptyMap()
        );
        
        // Act - Generate the HTML content
        HtmlToPdfReportServiceImpl service = new HtmlToPdfReportServiceImpl();
        
        // Use reflection to access the private method for testing
        var method = HtmlToPdfReportServiceImpl.class.getDeclaredMethod("generateRiskAnalysisHtmlWithSnippets", PdfReportService.RiskAnalysisReportRequest.class);
        method.setAccessible(true);
        
        String htmlContent = (String) method.invoke(service, request);
        
        // Assert - Check that HTML was generated
        assertNotNull(htmlContent);
        assertFalse(htmlContent.trim().isEmpty());
        
        // Debug - Write HTML to file for manual inspection
        Files.writeString(outputPath, htmlContent);
        System.out.println("HTML content written to: " + outputPath.toAbsolutePath());
        System.out.println("HTML length: " + htmlContent.length());
        
        // Basic HTML structure validation
        assertTrue(htmlContent.contains("<!DOCTYPE html>"));
        assertTrue(htmlContent.contains("<html"));
        assertTrue(htmlContent.contains("</html>"));
        assertTrue(htmlContent.contains("<head>"));
        assertTrue(htmlContent.contains("</head>"));
        assertTrue(htmlContent.contains("<body>"));
        assertTrue(htmlContent.contains("</body>"));
        
        // Check for Eclipse warning
        assertTrue(htmlContent.contains("Eclipse"));
        
        System.out.println("=== HTML Content Preview ===");
        System.out.println(htmlContent.substring(0, Math.min(1000, htmlContent.length())));
    }
}
