package adrianmikula.jakartamigration.testutil;

import org.objectweb.asm.*;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.jar.JarEntry;
import java.util.jar.JarOutputStream;
import java.util.jar.Manifest;
import java.util.jar.Attributes;

/**
 * Test utility for building JAR files with ASM-generated bytecode.
 * Provides a fluent API for defining classes and metadata for testing.
 */
public class TestJarBuilder {

    private final Map<String, byte[]> classFiles = new LinkedHashMap<>();
    private Manifest manifest = null;
    private String automaticModuleName = null;
    private String implementationTitle = null;
    private String pomXml = null;
    private String pomProperties = null;

    private TestJarBuilder() {}

    public static TestJarBuilder create() {
        return new TestJarBuilder();
    }

    public TestJarBuilder withClass(ClassSpec spec) {
        classFiles.put(spec.internalName, generateClassBytes(spec));
        return this;
    }

    public TestJarBuilder withClasses(ClassSpec... specs) {
        for (ClassSpec spec : specs) withClass(spec);
        return this;
    }

    public TestJarBuilder withManifest(String automaticModuleName, String implementationTitle) {
        this.automaticModuleName = automaticModuleName;
        this.implementationTitle = implementationTitle;
        return this;
    }

    public TestJarBuilder withManifest(String automaticModuleName) {
        return withManifest(automaticModuleName, null);
    }

    public TestJarBuilder withPomXml(String pomXml) {
        this.pomXml = pomXml;
        return this;
    }

    public TestJarBuilder withPomProperties(String pomProperties) {
        this.pomProperties = pomProperties;
        return this;
    }

    public void build(Path outputPath) throws IOException {
        Manifest mf = manifest != null ? manifest : createManifest();
        try (JarOutputStream jos = new JarOutputStream(
                new BufferedOutputStream(Files.newOutputStream(outputPath)), mf)) {
            for (Map.Entry<String, byte[]> entry : classFiles.entrySet()) {
                String classEntry = entry.getKey().replace('.', '/') + ".class";
                JarEntry je = new JarEntry(classEntry);
                jos.putNextEntry(je);
                jos.write(entry.getValue());
                jos.closeEntry();
            }
            if (pomXml != null) {
                JarEntry je = new JarEntry("META-INF/maven/unknown/artifact/pom.xml");
                jos.putNextEntry(je);
                jos.write(pomXml.getBytes(StandardCharsets.UTF_8));
                jos.closeEntry();
            }
            if (pomProperties != null) {
                JarEntry je = new JarEntry("META-INF/maven/unknown/artifact/pom.properties");
                jos.putNextEntry(je);
                jos.write(pomProperties.getBytes(StandardCharsets.UTF_8));
                jos.closeEntry();
            }
        }
    }

    private Manifest createManifest() {
        Manifest m = new Manifest();
        Attributes attrs = m.getMainAttributes();
        attrs.put(Attributes.Name.MANIFEST_VERSION, "1.0");
        if (automaticModuleName != null) {
            attrs.putValue("Automatic-Module-Name", automaticModuleName);
        }
        if (implementationTitle != null) {
            attrs.putValue("Implementation-Title", implementationTitle);
        }
        return m;
    }

    byte[] generateClassBytes(ClassSpec spec) {
        ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_MAXS | ClassWriter.COMPUTE_FRAMES);
        int access = spec.access | Opcodes.ACC_SUPER;
        cw.visit(Opcodes.V17, access, spec.internalName, spec.signature, spec.superName, spec.interfaces);

        for (FieldSpec f : spec.fields) {
            FieldVisitor fv = cw.visitField(f.access, f.name, f.descriptor, f.signature, f.value);
            for (AnnotationSpec ann : f.annotations) {
                AnnotationVisitor av = fv.visitAnnotation(ann.descriptor, ann.visible);
                for (Map.Entry<String, Object> kv : ann.values.entrySet()) {
                    av.visit(kv.getKey(), kv.getValue());
                }
                av.visitEnd();
            }
            fv.visitEnd();
        }

        for (MethodSpec m : spec.methods) {
            MethodVisitor mv = cw.visitMethod(m.access, m.name, m.descriptor, m.signature, m.exceptions);
            if ((m.access & (Opcodes.ACC_ABSTRACT | Opcodes.ACC_NATIVE)) == 0) {
                mv.visitCode();
                generateMethodBody(mv, m.descriptor);
                mv.visitMaxs(0, 0);
            }
            for (AnnotationSpec ann : m.annotations) {
                AnnotationVisitor av = mv.visitAnnotation(ann.descriptor, ann.visible);
                for (Map.Entry<String, Object> kv : ann.values.entrySet()) {
                    av.visit(kv.getKey(), kv.getValue());
                }
                av.visitEnd();
            }
            mv.visitEnd();
        }

        boolean hasConstructor = spec.methods.stream().anyMatch(m -> m.name.equals("<init>"));
        boolean isInterface = (spec.access & Opcodes.ACC_INTERFACE) != 0;
        boolean isAbstract = (spec.access & Opcodes.ACC_ABSTRACT) != 0;
        if (!isInterface && !isAbstract && !hasConstructor) {
            MethodVisitor mv = cw.visitMethod(Opcodes.ACC_PUBLIC, "<init>", "()V", null, null);
            mv.visitCode();
            mv.visitVarInsn(Opcodes.ALOAD, 0);
            mv.visitMethodInsn(Opcodes.INVOKESPECIAL, spec.superName, "<init>", "()V", false);
            mv.visitInsn(Opcodes.RETURN);
            mv.visitMaxs(0, 0);
            mv.visitEnd();
        }

        for (AnnotationSpec ann : spec.annotations) {
            AnnotationVisitor av = cw.visitAnnotation(ann.descriptor, ann.visible);
            for (Map.Entry<String, Object> kv : ann.values.entrySet()) {
                av.visit(kv.getKey(), kv.getValue());
            }
            av.visitEnd();
        }

        cw.visitEnd();
        return cw.toByteArray();
    }

    private void generateMethodBody(MethodVisitor mv, String descriptor) {
        char ret = descriptor.charAt(descriptor.lastIndexOf(')') + 1);
        switch (ret) {
            case 'V' -> mv.visitInsn(Opcodes.RETURN);
            case 'Z', 'B', 'C', 'S', 'I' -> {
                mv.visitInsn(Opcodes.ICONST_0);
                mv.visitInsn(Opcodes.IRETURN);
            }
            case 'J' -> {
                mv.visitLdcInsn(0L);
                mv.visitInsn(Opcodes.LRETURN);
            }
            case 'F' -> {
                mv.visitLdcInsn(0.0f);
                mv.visitInsn(Opcodes.FRETURN);
            }
            case 'D' -> {
                mv.visitLdcInsn(0.0);
                mv.visitInsn(Opcodes.DRETURN);
            }
            default -> {
                mv.visitInsn(Opcodes.ACONST_NULL);
                mv.visitInsn(Opcodes.ARETURN);
            }
        }
    }

    public static String toInternal(String fqcn) {
        return fqcn.replace('.', '/');
    }

    public static class ClassSpec {
        public String internalName;
        public int access = Opcodes.ACC_PUBLIC;
        public String superName = "java/lang/Object";
        public String[] interfaces = new String[0];
        public String signature = null;
        public List<FieldSpec> fields = new ArrayList<>();
        public List<MethodSpec> methods = new ArrayList<>();
        public List<AnnotationSpec> annotations = new ArrayList<>();

        public ClassSpec(String internalName) {
            this.internalName = internalName;
        }

        public static ClassSpec builder(String internalName) {
            return new ClassSpec(internalName);
        }

        public ClassSpec withAccess(int access) { this.access = access; return this; }
        public ClassSpec withSuper(String superFqcn) { this.superName = toInternal(superFqcn); return this; }
        public ClassSpec withSuperInternal(String superInternal) { this.superName = superInternal; return this; }
        public ClassSpec withInterface(String ifaceFqcn) {
            this.interfaces = Arrays.copyOf(this.interfaces, this.interfaces.length + 1);
            this.interfaces[this.interfaces.length - 1] = toInternal(ifaceFqcn);
            return this;
        }
        public ClassSpec withInterfaces(String... ifaceFqcn) {
            List<String> list = new ArrayList<>(Arrays.asList(this.interfaces));
            for (String i : ifaceFqcn) list.add(toInternal(i));
            this.interfaces = list.toArray(new String[0]);
            return this;
        }
        public ClassSpec withSignature(String signature) { this.signature = signature; return this; }
        public ClassSpec withField(FieldSpec field) { this.fields.add(field); return this; }
        public ClassSpec withMethod(MethodSpec method) { this.methods.add(method); return this; }
        public ClassSpec withAnnotation(AnnotationSpec annotation) { this.annotations.add(annotation); return this; }
        public ClassSpec build() { return this; }
    }

    public static class FieldSpec {
        public int access = Opcodes.ACC_PRIVATE;
        public String name;
        public String descriptor;
        public String signature = null;
        public Object value = null;
        public List<AnnotationSpec> annotations = new ArrayList<>();

        public FieldSpec(int access, String name, String descriptor) {
            this.access = access;
            this.name = name;
            this.descriptor = descriptor;
        }

        public static FieldSpec of(int access, String name, String descriptor) {
            return new FieldSpec(access, name, descriptor);
        }

        public FieldSpec withSignature(String signature) { this.signature = signature; return this; }
        public FieldSpec withValue(Object value) { this.value = value; return this; }
        public FieldSpec withAnnotation(AnnotationSpec ann) { this.annotations.add(ann); return this; }
    }

    public static class MethodSpec {
        public int access = Opcodes.ACC_PUBLIC;
        public String name;
        public String descriptor;
        public String signature = null;
        public String[] exceptions = null;
        public List<AnnotationSpec> annotations = new ArrayList<>();

        public MethodSpec(int access, String name, String descriptor) {
            this.access = access;
            this.name = name;
            this.descriptor = descriptor;
        }

        public static MethodSpec of(int access, String name, String descriptor) {
            return new MethodSpec(access, name, descriptor);
        }

        public MethodSpec withSignature(String signature) { this.signature = signature; return this; }
        public MethodSpec withExceptions(String... exceptions) { this.exceptions = exceptions; return this; }
        public MethodSpec withAnnotation(AnnotationSpec ann) { this.annotations.add(ann); return this; }
    }

    public static class AnnotationSpec {
        public String descriptor;
        public boolean visible = true;
        public Map<String, Object> values = new LinkedHashMap<>();

        public AnnotationSpec(String descriptor) {
            this.descriptor = descriptor;
        }

        public static AnnotationSpec of(String descriptor) {
            return new AnnotationSpec(descriptor);
        }

        public AnnotationSpec withValue(String key, Object value) {
            this.values.put(key, value);
            return this;
        }
    }

    public static TestJarBuilder createServletJar() {
        return create()
            .withClass(ClassSpec.builder("test/MyServlet")
                .withSuper("javax.servlet.http.HttpServlet")
                .withInterface("javax.servlet.Servlet")
                .withField(FieldSpec.of(Opcodes.ACC_PRIVATE, "request",
                    "Ljavax/servlet/http/HttpServletRequest;"))
                .withMethod(MethodSpec.of(Opcodes.ACC_PUBLIC, "service",
                    "(Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;)V")
                    .withAnnotation(AnnotationSpec.of("Ljavax/inject/Inject;")))
                .withAnnotation(AnnotationSpec.of("Ljavax/annotation/Generated;"))
                .build());
    }

    public static TestJarBuilder createPersistenceJar() {
        return create()
            .withClass(ClassSpec.builder("test/Entity")
                .withAnnotation(AnnotationSpec.of("Ljavax/persistence/Entity;"))
                .withField(FieldSpec.of(Opcodes.ACC_PRIVATE, "id", "J")
                    .withAnnotation(AnnotationSpec.of("Ljavax/persistence/Id;")))
                .withMethod(MethodSpec.of(Opcodes.ACC_PUBLIC, "getId", "()J"))
                .build());
    }

    public static TestJarBuilder createJakartaServletJar() {
        return create()
            .withClass(ClassSpec.builder("test/JakartaServlet")
                .withSuper("jakarta/servlet/http/HttpServlet")
                .withInterface("jakarta/servlet/Servlet")
                .withField(FieldSpec.of(Opcodes.ACC_PRIVATE, "request",
                    "Ljakarta/servlet/http/HttpServletRequest;"))
                .withMethod(MethodSpec.of(Opcodes.ACC_PUBLIC, "service",
                    "(Ljakarta/servlet/http/HttpServletRequest;Ljakarta/servlet/http/HttpServletResponse;)V"))
                .build());
    }

    public static TestJarBuilder createMixedNamespaceJar() {
        return create()
            .withClass(ClassSpec.builder("test/MixedServlet")
                .withSuper("javax/servlet/http/HttpServlet")
                .withInterface("jakarta/servlet/Servlet")
                .withField(FieldSpec.of(Opcodes.ACC_PRIVATE, "jakartaReq",
                    "Ljakarta/servlet/http/HttpServletRequest;"))
                .withField(FieldSpec.of(Opcodes.ACC_PRIVATE, "javaxReq",
                    "Ljavax/servlet/http/HttpServletRequest;"))
                .withMethod(MethodSpec.of(Opcodes.ACC_PUBLIC, "doSomething",
                    "(Ljavax/servlet/http/HttpServletRequest;Ljakarta/servlet/http/HttpServletResponse;)V"))
                .build());
    }

    public static TestJarBuilder createShadedJar() {
        return create()
            .withClass(ClassSpec.builder("com/example/shaded/javax/servlet/HttpServlet")
                .withSuper("java/lang/Object"))
            .withClass(ClassSpec.builder("com/example/repackaged/jakarta/persistence/Entity")
                .withSuper("java/lang/Object"));
    }

    public static TestJarBuilder createTestScopeJar() {
        return create()
            .withClass(ClassSpec.builder("test/ProductionClass")
                .withSuper("java/lang/Object"))
            .withClass(ClassSpec.builder("test/TestHelper")
                .withSuper("java/lang/Object"))
            .withClass(ClassSpec.builder("javax/servlet/TestServlet")
                .withSuper("java/lang/Object"));
    }
}
